/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nix.bookingsystem;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

import java.awt.event.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author cheng
 */
public class AccountsForm extends javax.swing.JFrame
{

  /**
   * Creates new form AccountsForm
   */
  public AccountsForm()
  {
    initComponents();
    Action deleteAction = new AbstractAction()
    {
      public void actionPerformed(ActionEvent e)
      {
        int confirm = JOptionPane.showConfirmDialog(_accountTable, "Delete confirmation");
        if (confirm != 0) return;
        JTable table = (JTable)e.getSource();
        int modelRow = Integer.valueOf( e.getActionCommand() );
        ((DefaultTableModel)table.getModel()).removeRow(modelRow);
      }
    };

    ButtonColumn buttonColumn = new ButtonColumn(_accountTable, deleteAction, 2);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    _accountsTitle = new javax.swing.JLabel();
    _accountScroller = new javax.swing.JScrollPane();
    _accountTable = new javax.swing.JTable();
    _addButton = new javax.swing.JButton();
    _saveButton = new javax.swing.JButton();
    _cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    _accountsTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
    _accountsTitle.setText("Accounts");

    _accountTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "Username", "Password", ""
      }
    ));
    _accountTable.setToolTipText("");
    _accountScroller.setViewportView(_accountTable);

    _addButton.setBackground(new java.awt.Color(59, 114, 87));
    _addButton.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
    _addButton.setForeground(new java.awt.Color(255, 255, 255));
    _addButton.setText("ADD");
    _addButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _addButtonActionPerformed(evt);
      }
    });

    _saveButton.setBackground(new java.awt.Color(59, 112, 114));
    _saveButton.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
    _saveButton.setForeground(new java.awt.Color(255, 255, 255));
    _saveButton.setText("SAVE");
    _saveButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _saveButtonActionPerformed(evt);
      }
    });

    _cancelButton.setBackground(new java.awt.Color(114, 114, 114));
    _cancelButton.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
    _cancelButton.setForeground(new java.awt.Color(255, 255, 255));
    _cancelButton.setText("CANCEL");
    _cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _cancelButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(55, 55, 55)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(_saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_cancelButton))
              .addComponent(_accountScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(_addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(_accountsTitle))
        .addContainerGap(234, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(52, 52, 52)
        .addComponent(_accountsTitle)
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(_accountScroller, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(_addButton))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_saveButton)
          .addComponent(_cancelButton))
        .addContainerGap(90, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void _addButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__addButtonActionPerformed
  {//GEN-HEADEREND:event__addButtonActionPerformed
    DefaultTableModel model = (DefaultTableModel) _accountTable.getModel();
    model.addRow(new Object[]{"newUser", "", "Delete"});
  }//GEN-LAST:event__addButtonActionPerformed

  private void _saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__saveButtonActionPerformed
  {//GEN-HEADEREND:event__saveButtonActionPerformed
    DefaultTableModel model = (DefaultTableModel) _accountTable.getModel();
    int rowCount = model.getRowCount();
    
    // validate if there are any duplicated usernames
    ArrayList<String> usernames = new ArrayList<>();
    
    for (int r=0; r < rowCount; r++)
    {
      String username = (String) model.getValueAt(r, 0);
      if (!usernames.contains(username))
        usernames.add(username);
      else
      {
        JOptionPane.showMessageDialog(_accountTable, "There are duplicated accounts!");
        return;
      }
    }
    
    SaveAccounts(rowCount, model);
  }//GEN-LAST:event__saveButtonActionPerformed

  private void _cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__cancelButtonActionPerformed
  {//GEN-HEADEREND:event__cancelButtonActionPerformed
    BookingSystem.SwitchForm(BookingSystem.loginForm);
  }//GEN-LAST:event__cancelButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(AccountsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(AccountsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(AccountsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(AccountsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new AccountsForm().setVisible(true);
      }
    });
  }
  
  public void InitializeAccounts()
  {
    DefaultTableModel model = (DefaultTableModel) _accountTable.getModel();
    model.setRowCount(0);
    
    ArrayList<Account> accounts = BookingSystem.accountManager.getAccounts();
    for (Account account : accounts)
      model.addRow(new Object[]{account.username, account.password, "Delete"});
  }
  
  private void SaveAccounts(int rowCount, DefaultTableModel model)
  {
    BookingSystem.accountManager.DeleteAllAccounts();
    for (int r=0; r < rowCount; r++)
    {
      String username = (String) model.getValueAt(r, 0);
      String password = (String) model.getValueAt(r, 1);
      BookingSystem.accountManager.CreateAccount(username, password);
    }
    
    try
    {
      BookingSystem.accountManager.SaveAccounts();
    } catch (IOException ex)
    {
      Logger.getLogger(AccountsForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    BookingSystem.SwitchForm(BookingSystem.loginForm);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane _accountScroller;
  private javax.swing.JTable _accountTable;
  private javax.swing.JLabel _accountsTitle;
  private javax.swing.JButton _addButton;
  private javax.swing.JButton _cancelButton;
  private javax.swing.JButton _saveButton;
  // End of variables declaration//GEN-END:variables
}
