/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nix.bookingsystem;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;

/**
 *
 * @author cheng
 */
public class BookingForm extends javax.swing.JFrame
{

  /**
   * Creates new form BookingForm
   */
  public BookingForm()
  {
    initComponents();
    _imageWidth = _roomImage.getWidth();
    
    PlainDocument doc;    
    doc = (PlainDocument) _ICField.getDocument();
    doc.setDocumentFilter(new IntFilter());
    
    doc = (PlainDocument) _phoneField.getDocument();
    doc.setDocumentFilter(new IntFilter());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    _roomImage = new javax.swing.JLabel();
    _roomNameLabel = new javax.swing.JLabel();
    _nameLabel = new javax.swing.JLabel();
    _nameField = new javax.swing.JTextField();
    _ICField = new javax.swing.JTextField();
    _ICLabel = new javax.swing.JLabel();
    _phoneLabel = new javax.swing.JLabel();
    _phoneField = new javax.swing.JTextField();
    _emailField = new javax.swing.JTextField();
    _emailLabel = new javax.swing.JLabel();
    _startDateLabel = new javax.swing.JLabel();
    _endDateLabel = new javax.swing.JLabel();
    _startDateChooser = new com.toedter.calendar.JDateChooser();
    _endDateChooser = new com.toedter.calendar.JDateChooser();
    _bookButton = new javax.swing.JButton();
    _cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    _roomNameLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
    _roomNameLabel.setForeground(new java.awt.Color(142, 196, 196));
    _roomNameLabel.setText("RoomName");

    _nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _nameLabel.setText("Name:");

    _ICLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _ICLabel.setText("IC:");

    _phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _phoneLabel.setText("Phone Number:");

    _emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _emailLabel.setText("Email:");

    _startDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _startDateLabel.setText("Start Date:");

    _endDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _endDateLabel.setText("End Date:");

    _startDateChooser.setEnabled(false);

    _endDateChooser.setEnabled(false);

    _bookButton.setBackground(new java.awt.Color(111, 146, 147));
    _bookButton.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
    _bookButton.setText("BOOK");
    _bookButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _bookButtonActionPerformed(evt);
      }
    });

    _cancelButton.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
    _cancelButton.setText("CANCEL");
    _cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _cancelButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(_roomImage, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(46, 46, 46)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(_roomNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(layout.createSequentialGroup()
              .addComponent(_nameLabel)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
              .addComponent(_ICLabel)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(_ICField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
              .addComponent(_phoneLabel)
              .addGap(62, 62, 62)
              .addComponent(_phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(_emailLabel)
                .addComponent(_startDateLabel)
                .addComponent(_endDateLabel))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                  .addComponent(_bookButton)
                  .addGap(18, 18, 18)
                  .addComponent(_cancelButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(_emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                  .addComponent(_startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(_endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        .addContainerGap(64, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(_roomImage, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(_roomNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(_nameLabel)
              .addComponent(_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(_ICLabel)
              .addComponent(_ICField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(_phoneLabel)
              .addComponent(_phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(_emailLabel)
              .addComponent(_emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(_startDateLabel)
              .addComponent(_startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(_endDateLabel))
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_bookButton)
          .addComponent(_cancelButton))
        .addContainerGap(74, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void _cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__cancelButtonActionPerformed
  {//GEN-HEADEREND:event__cancelButtonActionPerformed
    BookingSystem.roomsForm.FilterRooms();
    BookingSystem.SwitchForm(BookingSystem.roomsForm);
  }//GEN-LAST:event__cancelButtonActionPerformed

  private void _bookButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__bookButtonActionPerformed
  {//GEN-HEADEREND:event__bookButtonActionPerformed
    String name = _nameField.getText();
    String IC = _ICField.getText();
    String phone = _phoneField.getText();
    String email = _emailField.getText();

    _currBooking.SetBookDetail(name, IC, phone, email, BookingSystem.currUser);
    // validation
    String validation = _currBooking.ValidateBookingDetails();
    if (validation != null)
    {
      JOptionPane.showMessageDialog(this, validation);
      return;
    }
    _currBooking.checkout = false;
    BookingSystem.bookingManager.AddBooking(_currBooking);

    // save bookings
    try
    {
      BookingSystem.bookingManager.SaveBookings();
      JOptionPane.showMessageDialog(this, "Data saved successfully!");
      BookingSystem.roomsForm.FilterRooms();
      BookingSystem.SwitchForm(BookingSystem.roomsForm);
    } catch (IOException ex)
    {
      Logger.getLogger(BookingForm.class.getName()).log(Level.SEVERE, null, ex);
      JOptionPane.showMessageDialog(this, "An error occured while saving booking data...");
    }
  }//GEN-LAST:event__bookButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new BookingForm().setVisible(true);
      }
    });
  }
  
  public void InitializeBookingRoom(Booking booking, Room room)
  {
    // initialize image
    ImageIcon imageIcon = new ImageIcon(room.imageName);
    float width = imageIcon.getIconWidth();
    float height = imageIcon.getIconHeight();
    
    Image image = imageIcon.getImage();
    image = image.getScaledInstance(
      (int)_imageWidth, (int)(_imageWidth/width*height), Image.SCALE_SMOOTH
    );
    imageIcon.setImage(image);
    _roomImage.setIcon(imageIcon);

    // initialize room name
    _roomNameLabel.setText(room.name);

    // initialize date
    _startDateChooser.setDate(booking.startDate);
    _endDateChooser.setDate(booking.endDate);
    
    // set booking
    _currBooking = booking;
    
    // clear fields
    _nameField.setText("");
    _ICField.setText("");
    _phoneField.setText("");
    _emailField.setText("");
  }
  
  private float _imageWidth;
  private Booking _currBooking;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField _ICField;
  private javax.swing.JLabel _ICLabel;
  private javax.swing.JButton _bookButton;
  private javax.swing.JButton _cancelButton;
  private javax.swing.JTextField _emailField;
  private javax.swing.JLabel _emailLabel;
  private com.toedter.calendar.JDateChooser _endDateChooser;
  private javax.swing.JLabel _endDateLabel;
  private javax.swing.JTextField _nameField;
  private javax.swing.JLabel _nameLabel;
  private javax.swing.JTextField _phoneField;
  private javax.swing.JLabel _phoneLabel;
  private javax.swing.JLabel _roomImage;
  private javax.swing.JLabel _roomNameLabel;
  private com.toedter.calendar.JDateChooser _startDateChooser;
  private javax.swing.JLabel _startDateLabel;
  // End of variables declaration//GEN-END:variables
}
