/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nix.bookingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author cheng
 */
public class LoginForm extends javax.swing.JFrame {

  /**
   * Creates new form MainForm
   */
  public LoginForm() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    _titleLabel = new javax.swing.JLabel();
    _loginPanel = new javax.swing.JPanel();
    _loginTitle = new javax.swing.JLabel();
    _usernameLabel = new javax.swing.JLabel();
    _passwordLabel = new javax.swing.JLabel();
    _usernameField = new javax.swing.JTextField();
    _loginButton = new javax.swing.JButton();
    _passwordField = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1000, 600));

    _titleLabel.setFont(new java.awt.Font("Colonna MT", 0, 36)); // NOI18N
    _titleLabel.setText("The Grand Hotel");
    _titleLabel.setToolTipText("");

    _loginTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
    _loginTitle.setText("LOGIN");

    _usernameLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
    _usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    _usernameLabel.setText("Username:");

    _passwordLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
    _passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    _passwordLabel.setText("Password:");

    _usernameField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _usernameFieldActionPerformed(evt);
      }
    });

    _loginButton.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
    _loginButton.setText("LOGIN");
    _loginButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _loginButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout _loginPanelLayout = new javax.swing.GroupLayout(_loginPanel);
    _loginPanel.setLayout(_loginPanelLayout);
    _loginPanelLayout.setHorizontalGroup(
      _loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(_loginPanelLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(_loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(_loginButton)
          .addGroup(_loginPanelLayout.createSequentialGroup()
            .addGroup(_loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(_passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(_loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(_usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(32, 32, 32)
            .addGroup(_loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(_usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(60, Short.MAX_VALUE))
    );
    _loginPanelLayout.setVerticalGroup(
      _loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(_loginPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(_loginTitle)
        .addGap(59, 59, 59)
        .addGroup(_loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_usernameLabel)
          .addComponent(_usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(_loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_passwordLabel)
          .addComponent(_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(48, 48, 48)
        .addComponent(_loginButton)
        .addContainerGap(78, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(_loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(_titleLabel))
        .addContainerGap(416, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(_titleLabel)
        .addGap(52, 52, 52)
        .addComponent(_loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(158, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void _loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__loginButtonActionPerformed
    String username = _usernameField.getText();
    String password = _passwordField.getText();

    if (username.equals("admin") && password.equals("admin"))
    {
      BookingSystem.accountsForm.InitializeAccounts();
      BookingSystem.SwitchForm(BookingSystem.accountsForm);
      return;
    } else
    {
      Account loginAccount = new Account(username, password);
      int accountNum = BookingSystem.accountManager.HasAccount(loginAccount);
      if (accountNum != -1)
      {
        LoginSuccessful();
        return;
      }
    }
    
    LoginFail();
  }//GEN-LAST:event__loginButtonActionPerformed

  private void LoginSuccessful()
  {
    BookingSystem.SwitchForm(BookingSystem.hotelsForm);
  }
  
  private void LoginFail()
  {
    JOptionPane.showMessageDialog(this, "Invalid password or username.");
  }
  
  private void _usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__usernameFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event__usernameFieldActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton _loginButton;
  private javax.swing.JPanel _loginPanel;
  private javax.swing.JLabel _loginTitle;
  private javax.swing.JPasswordField _passwordField;
  private javax.swing.JLabel _passwordLabel;
  private javax.swing.JLabel _titleLabel;
  private javax.swing.JTextField _usernameField;
  private javax.swing.JLabel _usernameLabel;
  // End of variables declaration//GEN-END:variables
}
