/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nix.bookingsystem;

import java.time.Duration;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author cheng
 */
public class ReceiptForm extends javax.swing.JFrame
{

  /**
   * Creates new form ReceiptForm
   */
  public ReceiptForm()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    _manageBookingTitle = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    _emailLabel = new javax.swing.JLabel();
    _startDateLabel = new javax.swing.JLabel();
    _endDateLabel = new javax.swing.JLabel();
    _startDateChooser = new com.toedter.calendar.JDateChooser();
    _nameLabel = new javax.swing.JLabel();
    _endDateChooser = new com.toedter.calendar.JDateChooser();
    _nameField = new javax.swing.JTextField();
    _ICField = new javax.swing.JTextField();
    _ICLabel = new javax.swing.JLabel();
    _phoneField = new javax.swing.JTextField();
    _phoneLabel = new javax.swing.JLabel();
    _emailField = new javax.swing.JTextField();
    _doneButton = new javax.swing.JButton();
    _roomLabel = new javax.swing.JLabel();
    _roomField = new javax.swing.JTextField();
    _priceLabel = new javax.swing.JLabel();
    _priceField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    _manageBookingTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
    _manageBookingTitle.setText("Receipt");

    _emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _emailLabel.setText("Email:");

    _startDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _startDateLabel.setText("Start Date:");

    _endDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _endDateLabel.setText("End Date:");

    _startDateChooser.setEnabled(false);

    _nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _nameLabel.setText("Name:");

    _endDateChooser.setEnabled(false);

    _nameField.setEnabled(false);

    _ICField.setEnabled(false);

    _ICLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _ICLabel.setText("IC:");

    _phoneField.setEnabled(false);

    _phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _phoneLabel.setText("Phone Number:");

    _emailField.setEnabled(false);

    _doneButton.setFont(new java.awt.Font("Maiandra GD", 1, 12)); // NOI18N
    _doneButton.setText("DONE");
    _doneButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _doneButtonActionPerformed(evt);
      }
    });

    _roomLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _roomLabel.setText("Room:");

    _roomField.setEnabled(false);

    _priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    _priceLabel.setText("Price:");

    _priceField.setEnabled(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_doneButton))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(_nameLabel)
              .addComponent(_ICLabel)
              .addComponent(_emailLabel)
              .addComponent(_startDateLabel)
              .addComponent(_endDateLabel)
              .addComponent(_phoneLabel)
              .addComponent(_roomLabel)
              .addComponent(_priceLabel))
            .addGap(24, 24, 24)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(_emailField)
              .addComponent(_nameField, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(_ICField, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(_phoneField, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(_startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
              .addComponent(_endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(_roomField, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(_priceField, javax.swing.GroupLayout.Alignment.TRAILING))))
        .addGap(30, 30, 30))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_nameLabel)
          .addComponent(_nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_ICLabel)
          .addComponent(_ICField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_phoneLabel)
          .addComponent(_phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(_emailLabel)
          .addComponent(_emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(_startDateLabel)
          .addComponent(_startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(_endDateLabel))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(_endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(_roomLabel))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(_roomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(_priceLabel))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(_priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
        .addComponent(_doneButton)
        .addGap(171, 171, 171))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(_manageBookingTitle)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(_manageBookingTitle)
        .addGap(18, 18, 18)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void _doneButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__doneButtonActionPerformed
  {//GEN-HEADEREND:event__doneButtonActionPerformed
    BookingSystem.SwitchForm(BookingSystem.manageBookingForm);
  }//GEN-LAST:event__doneButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(ReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new ReceiptForm().setVisible(true);
      }
    });
  }
  
  public void InitializeReceipt(Booking booking)
  {
    ArrayList<Room> _rooms = BookingSystem.roomManager.getRooms();
    _nameField.setText(booking.customerName);
    _ICField.setText(booking.IC);
    _phoneField.setText(booking.phoneNumber);
    _emailField.setText(booking.email);
    _startDateChooser.setDate(booking.startDate);
    _endDateChooser.setDate(booking.endDate);
    _roomField.setText(_rooms.get(booking.roomIdx).name);

    float price = (float)booking.endDate.compareTo(booking.startDate)*(350 + 10);
    price += price * 0.1;
    _priceField.setText("RM " + String.format("%.2f", price));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField _ICField;
  private javax.swing.JLabel _ICLabel;
  private javax.swing.JButton _doneButton;
  private javax.swing.JTextField _emailField;
  private javax.swing.JLabel _emailLabel;
  private com.toedter.calendar.JDateChooser _endDateChooser;
  private javax.swing.JLabel _endDateLabel;
  private javax.swing.JLabel _manageBookingTitle;
  private javax.swing.JTextField _nameField;
  private javax.swing.JLabel _nameLabel;
  private javax.swing.JTextField _phoneField;
  private javax.swing.JLabel _phoneLabel;
  private javax.swing.JTextField _priceField;
  private javax.swing.JLabel _priceLabel;
  private javax.swing.JTextField _roomField;
  private javax.swing.JLabel _roomLabel;
  private com.toedter.calendar.JDateChooser _startDateChooser;
  private javax.swing.JLabel _startDateLabel;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
