/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nix.bookingsystem;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author cheng
 */
public class RoomsForm extends javax.swing.JFrame
{

  /**
   * Creates new form roomsForm
   */
  public RoomsForm()
  {
    initComponents();
    _jungleContentScroll.getVerticalScrollBar().setUnitIncrement(16);
    _jungleContentScroll.getHorizontalScrollBar().setUnitIncrement(16);
    _seaContentScroll.getVerticalScrollBar().setUnitIncrement(16);
    _seaContentScroll.getHorizontalScrollBar().setUnitIncrement(16);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    _accountsTitle = new javax.swing.JLabel();
    _splitPane = new javax.swing.JSplitPane();
    _junglePanel = new javax.swing.JPanel();
    _jungleTitlePanel = new javax.swing.JPanel();
    _jungleTitle = new javax.swing.JLabel();
    _jungleContentScroll = new javax.swing.JScrollPane();
    _jungleContentPanel = new javax.swing.JPanel();
    _seaPanel = new javax.swing.JPanel();
    _seaTitlePanel = new javax.swing.JPanel();
    _seaTitle = new javax.swing.JLabel();
    _seaContentScroll = new javax.swing.JScrollPane();
    _seaContentPanel = new javax.swing.JPanel();
    _buttonsPanel = new javax.swing.JPanel();
    _logoutButton = new javax.swing.JButton();
    _manageBookingButton = new javax.swing.JButton();
    _startDateChooser = new com.toedter.calendar.JDateChooser();
    _endDateChooser = new com.toedter.calendar.JDateChooser();
    _startingDateLabel = new javax.swing.JLabel();
    _endingDateLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    _accountsTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
    _accountsTitle.setText("Hotel Rooms");

    _splitPane.setDividerLocation(500);
    _splitPane.setResizeWeight(0.5);

    _jungleTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
    _jungleTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    _jungleTitle.setText("Jungle View");

    javax.swing.GroupLayout _jungleTitlePanelLayout = new javax.swing.GroupLayout(_jungleTitlePanel);
    _jungleTitlePanel.setLayout(_jungleTitlePanelLayout);
    _jungleTitlePanelLayout.setHorizontalGroup(
      _jungleTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(_jungleTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    _jungleTitlePanelLayout.setVerticalGroup(
      _jungleTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(_jungleTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout _jungleContentPanelLayout = new javax.swing.GroupLayout(_jungleContentPanel);
    _jungleContentPanel.setLayout(_jungleContentPanelLayout);
    _jungleContentPanelLayout.setHorizontalGroup(
      _jungleContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 498, Short.MAX_VALUE)
    );
    _jungleContentPanelLayout.setVerticalGroup(
      _jungleContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 466, Short.MAX_VALUE)
    );

    _jungleContentScroll.setViewportView(_jungleContentPanel);

    javax.swing.GroupLayout _junglePanelLayout = new javax.swing.GroupLayout(_junglePanel);
    _junglePanel.setLayout(_junglePanelLayout);
    _junglePanelLayout.setHorizontalGroup(
      _junglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(_jungleTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(_jungleContentScroll)
    );
    _junglePanelLayout.setVerticalGroup(
      _junglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(_junglePanelLayout.createSequentialGroup()
        .addComponent(_jungleTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(_jungleContentScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
    );

    _splitPane.setLeftComponent(_junglePanel);

    _seaTitle.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
    _seaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    _seaTitle.setText("Sea View");

    javax.swing.GroupLayout _seaTitlePanelLayout = new javax.swing.GroupLayout(_seaTitlePanel);
    _seaTitlePanel.setLayout(_seaTitlePanelLayout);
    _seaTitlePanelLayout.setHorizontalGroup(
      _seaTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(_seaTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    _seaTitlePanelLayout.setVerticalGroup(
      _seaTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(_seaTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout _seaContentPanelLayout = new javax.swing.GroupLayout(_seaContentPanel);
    _seaContentPanel.setLayout(_seaContentPanelLayout);
    _seaContentPanelLayout.setHorizontalGroup(
      _seaContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 488, Short.MAX_VALUE)
    );
    _seaContentPanelLayout.setVerticalGroup(
      _seaContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 472, Short.MAX_VALUE)
    );

    _seaContentScroll.setViewportView(_seaContentPanel);

    javax.swing.GroupLayout _seaPanelLayout = new javax.swing.GroupLayout(_seaPanel);
    _seaPanel.setLayout(_seaPanelLayout);
    _seaPanelLayout.setHorizontalGroup(
      _seaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(_seaTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(_seaContentScroll)
    );
    _seaPanelLayout.setVerticalGroup(
      _seaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(_seaPanelLayout.createSequentialGroup()
        .addComponent(_seaTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(_seaContentScroll))
    );

    _splitPane.setRightComponent(_seaPanel);

    _logoutButton.setBackground(new java.awt.Color(128, 97, 97));
    _logoutButton.setText("Logout");
    _logoutButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _logoutButtonActionPerformed(evt);
      }
    });

    _manageBookingButton.setBackground(new java.awt.Color(74, 102, 89));
    _manageBookingButton.setText("Manage Bookings");
    _manageBookingButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        _manageBookingButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout _buttonsPanelLayout = new javax.swing.GroupLayout(_buttonsPanel);
    _buttonsPanel.setLayout(_buttonsPanelLayout);
    _buttonsPanelLayout.setHorizontalGroup(
      _buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, _buttonsPanelLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(_manageBookingButton)
        .addGap(18, 18, 18)
        .addComponent(_logoutButton)
        .addContainerGap())
    );
    _buttonsPanelLayout.setVerticalGroup(
      _buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(_buttonsPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(_buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(_logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(_manageBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        .addContainerGap())
    );

    _startingDateLabel.setText("Starting Date");

    _endingDateLabel.setText("Ending Date");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(_accountsTitle)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(_startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(_startingDateLabel))
            .addGap(70, 70, 70)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(_endingDateLabel)
              .addComponent(_endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(118, 118, 118)
            .addComponent(_buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(_splitPane)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(_accountsTitle))
          .addGroup(layout.createSequentialGroup()
            .addComponent(_startingDateLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(_startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(_endingDateLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(_endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(_splitPane))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void _logoutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__logoutButtonActionPerformed
  {//GEN-HEADEREND:event__logoutButtonActionPerformed
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?");
    if (confirm != 0) return;
    BookingSystem.SwitchForm(BookingSystem.loginForm);
  }//GEN-LAST:event__logoutButtonActionPerformed

  private void _manageBookingButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event__manageBookingButtonActionPerformed
  {//GEN-HEADEREND:event__manageBookingButtonActionPerformed
    BookingSystem.manageBookingForm.InitializeBookings();
    BookingSystem.SwitchForm(BookingSystem.manageBookingForm);
  }//GEN-LAST:event__manageBookingButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(RoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new RoomsForm().setVisible(true);
      }
    });
  }

  public void InitializeRooms()
  {
    Date currDate = new Date();
    // today as in the next day (because we cannot book for today)
    Date today = new Date(currDate.getTime() + ONE_DAY);
    Date tomorrow = new Date(currDate.getTime() + 2*ONE_DAY);
    _startDateChooser.setDate(today);
    _endDateChooser.setDate(tomorrow);
    _startDateChooser.setMinSelectableDate(today);
    _endDateChooser.setMinSelectableDate(tomorrow);
    FilterRooms();

    _startDateChooser.getDateEditor().addPropertyChangeListener(
      new PropertyChangeListener()
      {
        @Override
        public void propertyChange(PropertyChangeEvent e)
        {
          if (e.getPropertyName().equals("date"))
          {
            FilterRooms();
            Date startDate = _startDateChooser.getDate();
            Date endDate = _endDateChooser.getDate();
            if (endDate.before(startDate) || endDate.equals(startDate))
            {
              endDate.setTime(startDate.getTime() + ONE_DAY);
              _endDateChooser.setDate(endDate);
            }
          }
        }
      }
    );
    _endDateChooser.getDateEditor().addPropertyChangeListener(
      new PropertyChangeListener()
      {
        @Override
        public void propertyChange(PropertyChangeEvent e)
        {
          if (e.getPropertyName().equals("date"))
          {
            FilterRooms();
            Date startDate = _startDateChooser.getDate();
            Date endDate = _endDateChooser.getDate();
            if (startDate.after(endDate) || startDate.equals(endDate))
            {
              startDate.setTime(endDate.getTime() - ONE_DAY);
              _startDateChooser.setDate(startDate);
            }
          }
        }
      }
    );
  }

  public void FilterRooms()
  {
    Date startDate = _startDateChooser.getDate();
    Date endDate = _endDateChooser.getDate();

    ArrayList<Booking> bookings = BookingSystem.bookingManager.getBookings();
    ArrayList<Integer> unavailableRoomIndices = new ArrayList<Integer>();
    for (Booking booking : bookings)
    {
      if (booking.checkout) continue;
      if (booking.CheckConflict(startDate, endDate) && !unavailableRoomIndices.contains(booking.roomIdx))
        unavailableRoomIndices.add(booking.roomIdx);
    }

    ArrayList<Room> rooms = BookingSystem.roomManager.getRooms();
    GenerateContents(_jungleContentPanel, rooms, 0, 10, unavailableRoomIndices);
    GenerateContents(_seaContentPanel, rooms, 10, 20, unavailableRoomIndices);
  }

  private void GenerateContents(
    JPanel panel, ArrayList<Room> rooms, int start, int end,
    ArrayList<Integer> unavailableRoomIndices
  )
  {
    GridLayout gridLayout = new GridLayout(10, 2, 10, 5);
    panel.removeAll();
    panel.setLayout(gridLayout);

    for (int r=start; r < end; r++)
    {
      if (unavailableRoomIndices.contains(r)) continue;
      Room room = rooms.get(r);
      JLabel iconLabel = new JLabel(room.icon, JLabel.HORIZONTAL);
      iconLabel.setHorizontalAlignment(JLabel.LEADING);
      panel.add(iconLabel);
      
      // detail panel
      JPanel detailPanel = new JPanel(new GridLayout(2, 1));
      JLabel nameLabel = new JLabel(room.name);
      nameLabel.setFont(new Font("Malgun Gothic Semilight", Font.BOLD, 14));
      nameLabel.setForeground(new Color(142, 196, 196));
      nameLabel.setHorizontalAlignment(JLabel.LEADING);
      detailPanel.add(nameLabel);
      
      JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
      IndexButton bookButton = new IndexButton("BOOK", r);
      bookButton.setFont(new Font("Maiandra GD", Font.BOLD, 12));
      bookButton.setBackground(new Color(0.15f, 0.23f, 0.28f));
      bookButton.addActionListener((java.awt.event.ActionEvent evt) ->
      {
        IndexButton button = (IndexButton)evt.getSource();
        Date startDate = _startDateChooser.getDate();
        Date endDate = _endDateChooser.getDate();
        Booking booking = new Booking(startDate, endDate, button.index);

        BookingSystem.bookingForm.InitializeBookingRoom(booking, room);
        BookingSystem.SwitchForm(BookingSystem.bookingForm);
      });
      buttonPanel.add(bookButton);
      detailPanel.add(buttonPanel);

      panel.add(detailPanel);
    }
    
    panel.repaint();
    panel.revalidate();
  }

  private static final long ONE_DAY = 24*60*60*1000;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel _accountsTitle;
  private javax.swing.JPanel _buttonsPanel;
  private com.toedter.calendar.JDateChooser _endDateChooser;
  private javax.swing.JLabel _endingDateLabel;
  private javax.swing.JPanel _jungleContentPanel;
  private javax.swing.JScrollPane _jungleContentScroll;
  private javax.swing.JPanel _junglePanel;
  private javax.swing.JLabel _jungleTitle;
  private javax.swing.JPanel _jungleTitlePanel;
  private javax.swing.JButton _logoutButton;
  private javax.swing.JButton _manageBookingButton;
  private javax.swing.JPanel _seaContentPanel;
  private javax.swing.JScrollPane _seaContentScroll;
  private javax.swing.JPanel _seaPanel;
  private javax.swing.JLabel _seaTitle;
  private javax.swing.JPanel _seaTitlePanel;
  private javax.swing.JSplitPane _splitPane;
  private com.toedter.calendar.JDateChooser _startDateChooser;
  private javax.swing.JLabel _startingDateLabel;
  // End of variables declaration//GEN-END:variables
}
